---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python
  children:
    prometheus:
      hosts:
        prom0.kzn.moc:
          public_ip: 129.10.5.138/24
        prom1.kzn.moc:
          public_ip: 129.10.5.139/24
        prom2.kzn.moc:
          public_ip: 129.10.5.140/24
      vars:
        ansible_user: root
        public_gateway: 129.10.5.1
