---
- hosts: prometheus
  tags: [facts]

- hosts: prometheus
  tags: [common]
  roles:
    - common
    - ovirt-guest
    - cgroupsv1
    - node-exporter

- hosts: prometheus
  tags: [network]
  roles:
    - firewall
    - public-interface

- hosts: prometheus
  tags: [storage]
  roles:
    - lvm

- hosts: prometheus[0]
  tags: [docker,docker-manager]
  roles:
    - docker-host
    - docker-swarm/manager

- hosts: prometheus[1:]
  tags: [docker,docker-worker]
  roles:
    - docker-host
    - docker-swarm/worker

- hosts: prometheus
  tags: [user]
  roles:
    - monitor-user
