---
- hosts: overcloud
  gather_facts: false
  roles:
    - node_exporter/service

- hosts: controller
  gather_facts: false
  roles:
    - node_exporter
    - machine_role

- hosts: network
  gather_facts: false
  roles:
    - node_exporter
    - machine_role

- hosts: compute
  gather_facts: false
  roles:
    - node_exporter
    - machine_role
    - libvirt_exporter
  tasks:
    - name: clean out old role.prom file
      file:
        path: "{{ textfile_collector_directory }}/role.prom"
        state: absent
