---
- hosts: undercloud
  gather_facts: false
  roles:
    - node_exporter/service
    - machine_role

- hosts: overcloud
  gather_facts: false
  roles:
    - node_exporter/service
    - machine_role

- hosts: compute
  gather_facts: false
  roles:
    - libvirt_exporter

- hosts: overcloud
  gather_facts: false
  roles:
    - node_exporter
  tasks:
    - name: clean out old role.prom file
      file:
        path: "{{ textfile_collector_directory }}/role.prom"
        state: absent
