---
version: "3"

volumes:
  prometheus_data_main:
  prometheus_run:

services:

  # The main Prometheus instance. This runs all the scrape jobs and writes
  # metrics to local storage and any remote write destinations.
  prom_main:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "prometheus_data_main:/prometheus"
      - "prometheus_run:/run/prometheus"
      - "./data/prom_main/prometheus.yml:/etc/prometheus/prometheus.yml"
    restart: always
    command: >-
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --storage.tsdb.min-block-duration=2h
      --storage.tsdb.max-block-duration=2h

  # Exports data about Cinder volumes.
  cinder_exporter:
    image: larsks/cinder-exporter
    volumes:
      - ./openstack:/etc/openstack
    command: -v --os-cloud ${OS_CLOUD}
    restart: always

  # Exports data about Keystone domains, projects, and users.
  keystone_exporter:
    image: larsks/keystone-exporter
    volumes:
      - ./openstack:/etc/openstack
    command: -v --os-cloud ${OS_CLOUD}
    restart: always

  # Exports data about hypervisors.
  nova_exporter:
    image: larsks/nova-exporter
    volumes:
      - ./openstack:/etc/openstack
    command: -v --os-cloud ${OS_CLOUD}
    restart: always

  # The sidecar ships data from the local Prometheus store to an object
  # storage service and also provides the query server with access to the
  # local data.
  thanos_sidecar:
    image: thanosio/thanos:master-2020-03-09-45d6bb8d
    volumes:
      - prometheus_data_main:/prometheus
      - ./thanos:/etc/thanos
    command: >-
      sidecar
      --prometheus.url http://prom_main:9090
      --tsdb.path /prometheus
      --objstore.config-file /etc/thanos/bucket_config.yml
      --http-address 0.0.0.0:19193
      --grpc-address 0.0.0.0:19090
    ports:
      - "19193:19193"
      - "19090:19090"
    restart: always
