---
- name: check if swarm is active
  command: >-
    docker node ls
  register: swarmcheck
  failed_when: false
  changed_when: swarmcheck.rc != 0

- name: initialize docker swarm
  command: >-
    docker swarm init --advertise-addr {{ ansible_eth0.ipv4.address }}
  when: swarmcheck is changed

- name: get join command
  command: >-
    docker swarm join-token worker -q
  register: join_token
