---
- name: ensure textfile collector directory exists
  file:
    path: "{{ textfile_collector_directory }}"
    state: directory

- name: write role metrics
  template:
    src: roles.prom
    dest: "{{ textfile_collector_directory }}/roles.prom"
